### ISSUE TITLE
TensorFlow v2.x not supported

### ISSUE THREAD

**Issue by ebertin** [mpaillassa/MaxiMask#1]
The current code is not TF v2.x compatible.
I managed to get it work under TF v2.3 by replacing
```py
import tensorflow as tf
```
with
```py
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
However it would be great to have native support to take advantage of TF2.x. TF1.x is obsoleted anyway.
Thanks!

**Comment by mpaillassa** [comment]
Finally done with #2 !
